FROM jupyter/minimal-notebook:python-3.9.13

RUN pip install ng_ai[networkx] && \
    rm -rf /home/$NB_USER/.cache/pip

ENV JUPYTER_TOKEN=nebula

# docker buildx build --push --platform linux/arm64/v8,linux/amd64 --tag weygu/ngai-jupyter-networkx:0.2.10.1 -f Dockerfile-jupyter-networkx .
# docker buildx build --push --platform linux/arm64/v8,linux/amd64 --tag weygu/ngai-jupyter-networkx:latest -f Dockerfile-jupyter-networkx .
