name: CD

on:
  release:
    types: [published]

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pdm install

      - name: Build and publish Python package
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pdm build
          pdm publish --username __token__ --password $PYPI_API_TOKEN

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push Jupyter Spark image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: docker/Dockerfile-jupyter-spark
      #     platforms: linux/amd64
      #     push: true
      #     tags: |
      #       weygu/pyspark-notebook-nebulagraph:${{ github.event.release.tag_name }}
      #       weygu/pyspark-notebook-nebulagraph:latest

      - name: Build and push Jupyter NetworkX image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile-jupyter-networkx
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            weygu/ngai-jupyter-networkx:${{ github.event.release.tag_name }}
            weygu/ngai-jupyter-networkx:latest