
name: Tests

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "*.md"

jobs:
  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Install
        run: pdm install
      - name: Run Lint
        run: pdm run lint
      - name: Run Unit Tests
        run: pdm run test
      - name: Run Integration Tests
        run: pdm run int-test
